export interface AnalyticsDataEntry {
  columnName: string;
  value: string | number | boolean | null;
}

export interface SessionMetaData {
  projectId: string;
  schemaVersion: string;
  sessionId: string;
  platform: string;
  startedAt: string;
  endedAt: string;
}

export interface SessionData {
  metaData: SessionMetaData;
  data: AnalyticsDataEntry[];
}

export interface SubmitSessionRequest {
  projectKey: string;
  sessionData: SessionData;
}

export interface Project {
  projectName: string;
  projectDescription: string;
  projectKey: string;   // secret for Unity SDK auth — generated as crypto.randomUUID() at creation
  createdAt: string;    // ISO 8601 timestamp
  updatedAt: string;    // ISO 8601 timestamp
}
// Firestore document ID = projectId (UUID, generated by backoffice at creation time)

export interface SchemaColumn {
  columnName: string;
  dataType?: 'string' | 'number' | 'boolean' | null;
}

export interface ProjectSchema {
  columns: SchemaColumn[];
  bakedAt: string;
}

export interface BakeSchemaRequest {
  projectId: string;
  projectKey: string;
  schemaVersion: string;
  columns: SchemaColumn[];
}

import { z } from 'zod';
import { Response } from 'express';

export const SchemaColumnZod = z.object({
  columnName: z.string().min(1),
  dataType: z.enum(['string', 'number', 'boolean']).nullable().optional(),
});

export const BakeSchemaBodyZod = z.object({
  projectId: z.string().min(1),
  projectKey: z.string().min(1),
  schemaVersion: z.string().min(1),
  columns: z.array(SchemaColumnZod).min(1),
});

export const SubmitSessionBodyZod = z.object({
  projectKey: z.string().min(1),
  sessionData: z.object({
    metaData: z.object({
      projectId: z.string().min(1),
      schemaVersion: z.string().min(1),
      sessionId: z.string().min(1),
      platform: z.string().min(1),
      startedAt: z.string().datetime({ offset: true }),
      endedAt: z.string().datetime({ offset: true }),
    }),
    data: z.array(z.object({
      columnName: z.string().min(1),
      value: z.union([z.string(), z.number(), z.boolean(), z.null()]),
    })),
  }),
});

export function validate<T>(schema: z.ZodSchema<T>, body: unknown, res: Response): T | null {
  const result = schema.safeParse(body);
  if (!result.success) {
    res.status(400).json({ error: 'Validation error', details: result.error.issues });
    return null;
  }
  return result.data;
}
