export interface AnalyticsDataEntry {
  columnName: string;
  value: string | number | boolean | null;
}

export interface SessionMetaData {
  projectId: string;
  schemaVersion: string;
  sessionId: string;
  platform: string;
  startedAt: string;
  endedAt: string;
}

export interface SessionData {
  metaData: SessionMetaData;
  data: AnalyticsDataEntry[];
}

export interface SubmitSessionRequest {
  sessionData: SessionData;
}

export interface Project {
  projectName: string;
  projectDescription: string;
  projectKey: string;   // secret for Unity SDK auth — generated as crypto.randomUUID() at creation
  createdAt: string;    // ISO 8601 timestamp
  updatedAt: string;    // ISO 8601 timestamp
}
// Firestore document ID = projectId (UUID, generated by backoffice at creation time)

export interface SchemaColumn {
  columnName: string;
  dataType?: 'string' | 'number' | 'boolean' | null;
}

export interface ProjectSchema {
  columns: SchemaColumn[];
  bakedAt: string;
}

export interface BakeSchemaRequest {
  projectId: string;
  projectKey: string;
  schemaVersion: string;
  columns: SchemaColumn[];
}
