using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace CRE.Analytics.Editor
{
    public static class AnalyticsCodeGenerator
    {
        private class CodeNode
        {
            public string Name;
            public AnalyticsField Field;
            public List<CodeNode> Children = new();
        }

        public static void Generate(AnalyticsSchema schema)
        {
            var root = BuildTree(schema);
            var code = GenerateCode(root, schema.schemaVersion);
            WriteToFile(code);
        }

        private static CodeNode BuildTree(AnalyticsSchema schema)
        {
            var root = new CodeNode { Name = "Analytics", Field = null };

            foreach (var field in schema.fields)
            {
                string[] segments = field.columnName.Split('/');
                CodeNode current = root;

                for (int i = 0; i < segments.Length; i++)
                {
                    string segment = segments[i];
                    bool isLeaf = (i == segments.Length - 1);

                    if (isLeaf)
                    {
                        var leafNode = new CodeNode
                        {
                            Name = segment,
                            Field = field
                        };
                        current.Children.Add(leafNode);
                    }
                    else
                    {
                        CodeNode child = current.Children.Find(n => n.Name == segment && n.Field == null);
                        if (child == null)
                        {
                            child = new CodeNode { Name = segment, Field = null };
                            current.Children.Add(child);
                        }
                        current = child;
                    }
                }
            }

            return root;
        }

        private static string GenerateCode(CodeNode root, string schemaVersion)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by CRE Analytics Bake — do not edit manually");
            sb.AppendLine($"// Schema version: {schemaVersion}");
            sb.AppendLine("using CRE.Analytics;");
            sb.AppendLine();
            sb.AppendLine("public static class Analytics");
            sb.AppendLine("{");

            GenerateNodeContent(sb, root, 1);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateNodeContent(StringBuilder sb, CodeNode node, int indentLevel)
        {
            string indent = new string(' ', indentLevel * 4);

            foreach (var child in node.Children)
            {
                if (child.Field != null)
                {
                    string methodName = "Set" + ToPascalCase(child.Name);
                    string csType = GetCSharpType(child.Field.type);
                    string fullColumnName = child.Field.columnName;

                    sb.AppendLine($"{indent}public static void {methodName}({csType} value) => CREAnalytics.Set(\"{fullColumnName}\", value);");
                }
                else
                {
                    string className = ToPascalCase(child.Name);
                    sb.AppendLine();
                    sb.AppendLine($"{indent}public static class {className}");
                    sb.AppendLine($"{indent}{{");

                    GenerateNodeContent(sb, child, indentLevel + 1);

                    sb.AppendLine($"{indent}}}");
                }
            }
        }

        private static string ToPascalCase(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
                return "Unknown";

            var normalized = RemoveDiacritics(input);
            var cleaned = new string(normalized.Where(c => char.IsLetterOrDigit(c) || char.IsWhiteSpace(c)).ToArray());
            
            var words = cleaned.Split(new[] { ' ' }, System.StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();

            foreach (var word in words)
            {
                if (word.Length > 0)
                {
                    sb.Append(char.ToUpper(word[0]));
                    if (word.Length > 1)
                        sb.Append(word.Substring(1));
                }
            }

            var result = sb.ToString();
            if (string.IsNullOrEmpty(result))
                return "Unknown";

            if (char.IsDigit(result[0]))
                result = "_" + result;

            return result;
        }

        private static string RemoveDiacritics(string text)
        {
            var normalizedString = text.Normalize(System.Text.NormalizationForm.FormD);
            var sb = new StringBuilder();

            foreach (var c in normalizedString)
            {
                var unicodeCategory = System.Globalization.CharUnicodeInfo.GetUnicodeCategory(c);
                if (unicodeCategory != System.Globalization.UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(c);
                }
            }

            return sb.ToString().Normalize(System.Text.NormalizationForm.FormC);
        }

        private static string GetCSharpType(AnalyticsFieldType type)
        {
            switch (type)
            {
                case AnalyticsFieldType.Int:
                    return "int";
                case AnalyticsFieldType.Float:
                    return "float";
                case AnalyticsFieldType.Bool:
                    return "bool";
                case AnalyticsFieldType.String:
                    return "string";
                case AnalyticsFieldType.Timestamp:
                    return "string";
                default:
                    return "string";
            }
        }

        private static void WriteToFile(string code)
        {
            string directory = "Assets/CREAnalytics/Generated";
            string filePath = Path.Combine(directory, "Analytics.cs");

            Directory.CreateDirectory(directory);
            File.WriteAllText(filePath, code);
        }
    }
}
